2020-03-17 15:21:44,446 ERROR: Exception on /login [GET] [in d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Users\chris.garland\Documents\Experimental\FlaskSB\app\routes.py", line 52, in login
    return render_template('login.html', title='Sign In', form=form)
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "D:\Users\chris.garland\AppData\Roaming\Python\Python36\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "D:\Users\chris.garland\AppData\Roaming\Python\Python36\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\Users\chris.garland\AppData\Roaming\Python\Python36\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Users\chris.garland\AppData\Roaming\Python\Python36\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\Users\chris.garland\Documents\Experimental\FlaskSB\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\Users\chris.garland\Documents\Experimental\FlaskSB\app\templates\base.html", line 24, in top-level template code
    {% block content %}{% endblock %}
  File "D:\Users\chris.garland\Documents\Experimental\FlaskSB\app\templates\login.html", line 24, in block "content"
    <p>Forgot your password?<a href="{{ url_for('rest_password_request') }}">Click to Reset</a></p>
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'rest_password_request'. Did you mean 'reset_password_request' instead?
2020-03-17 15:26:37,161 INFO: Microblog startup [in D:\Users\chris.garland\Documents\Experimental\FlaskSB\app\__init__.py:47]
2020-03-17 15:26:40,764 ERROR: Exception on /login [GET] [in d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Users\chris.garland\Documents\Experimental\FlaskSB\app\routes.py", line 52, in login
    return render_template('login.html', title='Sign In', form=form)
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "D:\Users\chris.garland\AppData\Roaming\Python\Python36\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "D:\Users\chris.garland\AppData\Roaming\Python\Python36\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\Users\chris.garland\AppData\Roaming\Python\Python36\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Users\chris.garland\AppData\Roaming\Python\Python36\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\Users\chris.garland\Documents\Experimental\FlaskSB\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\Users\chris.garland\Documents\Experimental\FlaskSB\app\templates\base.html", line 24, in top-level template code
    {% block content %}{% endblock %}
  File "D:\Users\chris.garland\Documents\Experimental\FlaskSB\app\templates\login.html", line 24, in block "content"
    <p>Forgot your password?<a href="{{ url_for('rest_password_request') }}">Click to Reset</a></p>
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "d:\users\chris.garland\appdata\local\programs\python\python36\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'rest_password_request'. Did you mean 'reset_password_request' instead?
